services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_api
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: finance_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: